function CleanRawFile(f)
%Rewrites raw file if it cannot be read by Pro51 due to extra data fields.
%
% 09.02.2017 - M. Hutnak

% % Remove any Previous Temporary Files Generated by AWK
if exist('RawData.tmp','file')
    delete('RawData.tmp');
end

% % INPUT FILE

if nargin==0
% Open gui to select filename
    [filename, pathname] = uigetfile({'*.raw'},'Pick an ROQ Probe Output File');

    % Validate the file/path
    if isequal(filename,0)||isequal(pathname,0)
        disp('File not found')
        H_error = errordlg('File not found or not valid');
        ErrorFlag=1;
        return
    else
        f=fullfile(pathname,filename);
    end
else
    [pathname,filename,ext]=fileparts(f);
    filename = [filename,ext];
end


fncname = 'CleanRawFile.tmp';
fnclean = fullfile(pathname,fncname);

% % Loop to read and write
fidi = fopen(f,'r');
fido = fopen(fnclean,'w');

blanklines = [];
i=1;
while i>0
    line=fgetl(fidi);
    if line==-1
        fclose(fidi);
        fclose(fido);
        i=0;
        break
    else
        if ~strcmp(line(1),'$')
            a=find(isspace(line));
            %disp(['cols ',int2str(length(a)),' : ',line]);
            if length(a)==25 && i>1
                disp(['line ',int2str(i),' cols = ',int2str(length(a)),' : ',line]);
                line = line(1:a(end));
                %fprintf(fido,'%s\n',line);
            else
                fprintf(fido,'%s\n',line);
            end
        else
            fprintf(fido,'%s\n',line);
        end
    end
    i=i+1;
end

% % Rename and clean up
fnsave = [filename,'.original'];
[success,~,~]= copyfile(fullfile(pathname,filename),fullfile(pathname,fnsave));
if success
    [success,~,~]=copyfile(fullfile(pathname,fncname),fullfile(pathname,filename));
    if ~success
        disp(message)
    else
        disp('Cleaned.')
    end
else
    disp(message);
end

delete(fullfile(pathname,fncname))
end



