function p51_CreatePenfile_ROQ(H,DATA)
% CreatePenfile called by Pro51.m to create a ROQ Probe Penfile
%
% Inclusion of the file Pro51_DefaultPenvals.mat in the present working
% directory containing ClientName, Datum, SensorID, Station, and Number
% of Thermistors facilitates populating the penfile fields.
%
%
% 2017 -- Michael Hutnak, Right On Q, Inc.
%         mhutnak@roqinc.com
%   
% Versions and Updates: V1.0 05.02.2017

disp('p51_CreatePenfile: Creating penfile...')

global H_penfig
global S_PenHandles

% -----------------------------
% Main figure, control frame, Exit/Quit frame

% Main Figure Window
H_penfig=figure('numbertitle','off', ...
    'name','Penfile Creation', ...
    'menubar','none');
set(gcf,'units','normalized','position',[0.4 0.4 0.4 0.4]);

% Main controls Frame
H_penfigframe = uicontrol(gcf,'style','frame',...
   'units','normalized',...
   'position',[0.05 0.05 0.90 0.90],...
   'backgroundcolor',[0.5 0.5 0.5]);

% Exit Controls Frame
H_frame_exit = uicontrol(gcf,'style','frame',...
   'units','normalized',...
   'position',[0.08 0.10 0.40 0.15]);

% Verify & Write Controls Frame
H_frame_output = uicontrol(gcf,'style','frame',...
   'units','normalized',...
   'position',[0.52 0.10 0.40 0.15]);


%  ---- CANCEL / VALIDATE & WRITE PENFILE ---- %
% Pushbutton to Quit
H_quit = uicontrol(gcf,'style','pushbutton',...
   'units','normalized',...
   'position',[0.125 0.125 0.300 0.090],...
   'string','Cancel',...
   'fontsize',16,...
   'callback',[...
   'global H_penfig;',...
   'close(H_penfig);']);

% Pushbutton to Validate Input Data
H_validate = uicontrol(gcf,'style','pushbutton',...
   'units','normalized',...
   'position',[0.540 0.125 0.175 0.090],...
   'string','Validate',...
   'fontsize',16,...
   'callback',[...
       'global S_PenHandles;',...
       'p51_Validate(S_PenHandles)']);
   
% Pushbutton to Write Penfile
H_writepenfile = uicontrol(gcf,'style','pushbutton',...
   'units','normalized',...
   'position',[0.725 0.125 0.175 0.090],...
   'string','Create',...
   'fontsize',16,...
   'enable','off',...
   'callback',[...
        'global H_penfig;',...
        'p51_WritePenFile_ROQ(H,DATA,S_PenHandles,H_penfig)']);
  
%  ---- STATIC TEXT BLOCK ---- 
% CLIENT
H_static_clientname = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.070 0.820 0.160 0.060],...
   'string','Client:',...
   'horizontalalignment','left',...
   'fontsize',16,...
   'backgroundcolor',[0.5 0.5 0.5]);

% STATION
H_static_station = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.070 0.720 0.160 0.060],...
   'string','Station:',...
   'horizontalalignment','left',...
   'fontsize',16,...
   'backgroundcolor',[0.5 0.5 0.5]);

% PENETRATION
H_static_penetration = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.520 0.720 0.160 0.060],...
   'string','Penetration:',...
   'horizontalalignment','left',...
   'fontsize',16,...
   'backgroundcolor',[0.5 0.5 0.5]);

% SENSOR
H_static_sensor = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.520 0.620 0.160 0.060],...
   'string','Sensor:',...
   'horizontalalignment','left',...
   'fontsize',16,...
   'backgroundcolor',[0.5 0.5 0.5]);

% DATUM
H_static_datum = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.520 0.520 0.160 0.060],...
   'string','Datum:',...
   'horizontalalignment','left',...
   'fontsize',16,...
   'backgroundcolor',[0.5 0.5 0.5]);

% INSTRUMENT
H_static_instrument = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.070 0.620 0.160 0.060],...
   'string','Instrument:',...
   'horizontalalignment','left',...
   'fontsize',16,...
   'backgroundcolor',[0.5 0.5 0.5]);

% THERMISTORS
H_static_thermistors = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.070 0.520 0.160 0.060],...
   'string','Thermistors:',...
   'horizontalalignment','left',...
   'fontsize',16,...
   'backgroundcolor',[0.5 0.5 0.5]);

% LATITUDE
H_static_lat = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.070 0.420 0.160 0.060],...
   'string','Latitude/Y:',...
   'horizontalalignment','left',...
   'fontsize',16,...
   'backgroundcolor',[0.5 0.5 0.5]);

% LONGITUDE
H_static_lon = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.520 0.420 0.160 0.060],...
   'string','Longitude/X:',...
   'horizontalalignment','left',...
   'fontsize',16,...
   'backgroundcolor',[0.5 0.5 0.5]);

% DEPTH
H_static_depth = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.070 0.320 0.160 0.060],...
   'string','Depth:',...
   'horizontalalignment','left',...
   'fontsize',16,...
   'backgroundcolor',[0.5 0.5 0.5]);

% TILT
H_static_tilt = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.520 0.320 0.160 0.060],...
   'string','Tilt (deg):',...
   'horizontalalignment','left',...
   'fontsize',16,...
   'backgroundcolor',[0.5 0.5 0.5]);

% ---- DYNAMIC TEXT ----
% Dynamic text that displays client name
H_clientname = uicontrol(gcf,'style','edit',...
   'units','normalized',...
   'position',[0.230 0.820 0.700 0.060],...
   'string','default',...
   'horizontalalignment','left',...
   'fontsize',16,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Dynamic text that displays station
H_station = uicontrol(gcf,'style','edit',...
   'units','normalized',...
   'position',[0.230 0.720 0.250 0.060],...
   'string','default',...
   'horizontalalignment','left',...
   'fontsize',16,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Dynamic text that displays instrument
H_instrument = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.230 0.620 0.250 0.060],...
   'string','default',...
   'horizontalalignment','left',...
   'fontsize',16,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Dynamic text that displays thermistors
H_thermistors = uicontrol(gcf,'style','edit',...
   'units','normalized',...
   'position',[0.230 0.520 0.250 0.060],...
   'string','default',...
   'horizontalalignment','left',...
   'fontsize',16,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Dynamic text that displays latitude
H_lat = uicontrol(gcf,'style','edit',...
   'units','normalized',...
   'position',[0.230 0.420 0.250 0.060],...
   'string','default',...
   'horizontalalignment','left',...
   'fontsize',16,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Dynamic text that displays depth
H_depth = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.230 0.320 0.250 0.060],...
   'string','default',...
   'horizontalalignment','left',...
   'fontsize',16,...
   'backgroundcolor',[0.5 0.5 0.5]);


% Dynamic text that displays pen
H_penetration = uicontrol(gcf,'style','edit',...
   'units','normalized',...
   'position',[0.680 0.720 0.250 0.060],...
   'string','default',...
   'horizontalalignment','left',...
   'fontsize',16,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Dynamic text that displays sensor
H_sensor = uicontrol(gcf,'style','edit',...
   'units','normalized',...
   'position',[0.680 0.620 0.250 0.060],...
   'string','default',...
   'horizontalalignment','left',...
   'fontsize',16,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Dynamic text that displays datum
H_datum = uicontrol(gcf,'style','edit',...
   'units','normalized',...
   'position',[0.680 0.520 0.250 0.060],...
   'string','default',...
   'horizontalalignment','left',...
   'fontsize',16,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Dynamic text that displays longitude
H_lon = uicontrol(gcf,'style','edit',...
   'units','normalized',...
   'position',[0.680 0.420 0.250 0.060],...
   'string','default',...
   'horizontalalignment','left',...
   'fontsize',16,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Dynamic text that displays tilt
H_tilt = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.680 0.320 0.250 0.060],...
   'string','default',...
   'horizontalalignment','left',...
   'fontsize',16,...
   'backgroundcolor',[0.5 0.5 0.5]);

% If Default Values Exist, Load and Populate
if exist('Pro51_DefaultPenvals.mat','file')
    load Pro51_DefaultPenvals.mat ;
    set(H_clientname,'string',Clientname);
    set(H_station,'string',Station);
    set(H_datum,'string',Datum);
    set(H_thermistors,'string',Thermistors);
    set(H_sensor,'string',Sensor);
end



% ------------ SET INPUT VALUES --------------- %
Depth  = DATA.Depth_dec;
Time   = DATA.Time_dec;
%T      = DATA.Tdec;
Tilt   = DATA.Tilt_dec;
record = DATA.Record_dec;
%record  = 1:1:length(Tilt);

record = record';
Depth  = Depth';


% Measurement Start and End
%msmt_start = H.Selections.Start_Pen.String;
%msmt_end   = H.Selections.End_Pen.String;

msmt_start = datenum(H.Selections.Start_Pen.String,'mm/dd/yy HH:MM:SS');
msmt_end   = datenum(H.Selections.End_Pen.String,'mm/dd/yy HH:MM:SS');

% QC on Year, may be 00 instead of 
loggerStart = datevec(datestr(Time));
loggerYear  = loggerStart(1,1);
if loggerYear < 2021
    loggerStart(:,1)=loggerStart(:,1)+2000;
    % Rebuild
    Time=datenum(loggerStart);
end
    

% Mean Depth and Tilt records within measurement period
%a = find(record>=str2num(msmt_start) & record<=str2num(msmt_end));
a = find(Time>=msmt_start & Time<=msmt_end);
if ~isempty(a)
    pen_depth = mean(Depth(a),'omitnan');
    pen_tilt  = mean(Tilt(a),'omitnan');
    pen_tilt  = sprintf('%2.1f',pen_tilt);
    pen_tilt  = str2num(pen_tilt);
else
    errordlg('No Data in Time Window','Error','modal')
    return
end


set(H_instrument,'string',logger);
set(H_tilt,'string',pen_tilt);
set(H_depth,'string',pen_depth);

% ------------ STRUCTURE WITH HANDLES --------------- %

S_PenHandles=struct('Client',H_clientname,'Station',H_station,...
    'Pen',H_penetration,'Sensor',H_sensor,'Datum',H_datum,...
    'Inst',H_instrument,'Therms',H_thermistors,'Lat',H_lat,...
    'Lon',H_lon,'H_Penfile',H_writepenfile,...
    'Tilt',H_tilt,'Depth',H_depth);

return

