function p51_Validate(S_PenHandles)
% p51_Validate confirms all data fields are populated for exporting a
% penfile
%
% 2015 -- Michael Hutnak, Right On Q, Inc.
%         mhutnak@roqinc.com
%   
% Versions and Updates: V3.0 05.12.2015

disp('p51_Validate: validating parameters for penfile...')

if  (isempty(S_PenHandles.Client.String) ...
 ||  isempty(S_PenHandles.Station.String) ...
 ||  isempty(S_PenHandles.Pen.String) ...
 ||  isempty(S_PenHandles.Sensor.String) ...
 ||  isempty(S_PenHandles.Datum.String) ...
 ||  isempty(S_PenHandles.Inst.String) ...
 ||  isempty(S_PenHandles.Therms.String) ...
 ||  isempty(S_PenHandles.Lat.String) ...
 ||  isempty(S_PenHandles.Lon.String)) ...
    h_error = errordlg('Fill Out All Fields','Error','modal'); ...
    uiwait(h_error); ...
else ...
    set(S_PenHandles.H_Penfile,'enable','on','backgroundcolor','g'); ...
end


