function [ymd,hms,accx,accy,accz,pwr,z,Traw] = p51_ScanUnix(H,f,fn)
%p51_ScanUnixQC Scan in Unix data 

% % Remove Temporary Files Generated by AWK
if exist('RawData.tmp','file')
    delete('RawData.tmp');
end

disp(' Unix - using awk...')
% Grab all lines with length > 80 (Data)
eval(['!awk ''length > 80'' ',f,' > RawData.tmp'])
% Grab all Acomms Report lines
eval(['!awk ''/RPT/'' ',f,' > ',fn,'_HReport.dat'])
% Grab all Heat Pulse Report lines
eval(['!awk ''/HSTART/'' ',f,' > ',fn,'_HPulse.dat'])

% Prep textscan for variable number of thermistors
NoTherm = H.Fileinfo.No_Thermistors.Value;
n       = repmat(['%n '],1,NoTherm);    % Thermistors 
%n       = repmat(['%n '],1,13);    % Thermistors - default 13
s       = repmat(['%s '],1,11);         % Time, Acc, depth

% Open the Data File and Scan in the data
fid = fopen('RawData.tmp','r');

C   = textscan(fid,[s n]);
fclose(fid);

% Initialize Matrix AllTdata (All Temperature Data)
l    = length(C{1});
Traw = NaN*zeros(NoTherm+1,l);

% Assign
ymd    = str2num(char(strrep(C{3},'-',' ')));
hms    = str2num(char(strrep(C{4},':',' ')));
accx   = str2num(char(strrep(C{6},'X','')));
accy   = str2num(char(strrep(C{7},'Y','')));
accz   = str2num(char(strrep(C{8},'Z','')));
pwr    = str2num(char(strrep(C{9},'V','')));
z      = str2num(char(strrep(C{10},'D','')));
for i=1:NoTherm
    foo = C{11+i}';
    Traw(i,1:length(foo))=foo;
end

% Restructure Traw with T1 in row 1, incrementing to Twater
Traw(NoTherm+1,:)=Traw(1,:);
Traw=Traw(2:end,:);
end

