function Pro51

% Main GUI for loading ROQ Probe data files and creating Penfiles, ASCII File, and
% Water Column files.
%
% USAGE: Pro51
%
% Pro51 opens a GUI to plot temperature, tilt, and depth for an ROQ heat
% flow probe raw file. The user can export the entire dataset as an ASCII
% file, extract water column upcast / downcast data, and create individual
% penfiles.
%
% Based on original PRO50.exe program.
%
% 2017 -- Michael Hutnak, Right On Q Inc.
%             mhutnak@roqinc.com
%   


% Versions and Updates: V3.0 05.12.2015
Version = '1.0';
Update  = '05.05.2017';

% Define Global Handles for Structures
global S_Axes
global S_Exe_Controls
global S_Selections
global S_Plot_Controls
global S_Selections_Lines
global S_FileInfo
%global S_Data
global H
%global DATA
global S_AxLims
global H_figure

% -----------------------------
% Main figure, control frame, Exit/Quit frame

% Main Figure Window
H_figure=figure('numbertitle','off', ...
    'name','Right On Q Inc - The Intelligent Choice', ...
    'menubar','none');
set(gcf,'units','normalized','position',[0 0 1 1]);
orient landscape

% Main controls Frame
H_frame_controls = uicontrol(gcf,'style','frame',...
   'units','normalized',...
   'position',[0.01 0.10 0.18 0.88],...
   'tooltipstring',['Version ' Version ' - Update ' Update ]);

% Exit Frame
H_frame_Exit = uicontrol(gcf,'style','frame',...
   'units','normalized',...
   'position',[0.01 0.02 0.18 0.07]);

%-------------------------------
% FIGURE AXIS

% Axis where thermal data will be displayed
rect = [0.25 0.42 0.70 0.56];
H_axis_raw = axes('position',rect,'color',[0.9 0.9 0.9],'box','on');

% Axis where Depth will be displayed
rect = [0.25 0.30 0.70 0.08];
H_axis_depth = axes('position',rect,'color',[0.9 0.9 0.9],'box','on');

% Axis where Acceleration will be displayed
rect = [0.25 0.18 0.70 0.08];
H_axis_accel = axes('position',rect,'color',[0.9 0.9 0.9],'box','on');

% Axis where Pitch & Roll will be displayed
rect = [0.25 0.05 0.70 0.08];
H_axis_tilt = axes('position',rect,'color',[0.9 0.9 0.9],'box','on');

%--------------------------
% Frame and Controls for Load, Create H2O Column File, Create Penfile

H_frame_load = uicontrol(gcf,'style','frame',...
   'units','normalized',...
   'position',[0.015 0.750 0.17 0.220],...
   'backgroundcolor',[0.5 0.5 0.5]);

H_frame_load2 = uicontrol(gcf,'style','frame',...
   'units','normalized',...
   'position',[0.020 0.914 0.160 0.050],...
   'backgroundcolor',[0.75 0.75 0.75]);

% Pushbutton to load a datafile
H_load = uicontrol(gcf,'style','pushbutton',...
   'units','normalized',...
   'position',[0.025 0.920 0.075 0.04],...
   'string','Load / Filter',...
   'fontsize',14,...
   'tooltipstring','Load an ROQ Heat Flow Probe file',...
   'callback',[...
        'global H;',...
        'global DATA;',...
        'H.Crop=0;',...
        'H.Exe_Controls.Crop.Enable=''off'';',...
        'H.Exe_Controls.Delete.Enable=''off'';',...
        'H.Plot_Controls.RawPlot.Enable=''off'';',...
        'H.Plot_Controls.CleanPlot.Enable=''off'';',...
        'H.Plot_Controls.DecimatedPlot.Enable=''off'';',...
        'p51_Reset(H);',...
        'ErrorFlag=p51_Load_ROQ(H);',...
        'if ErrorFlag==0;p51_Plot_ROQ(H,DATA);end;']);
    
% Pushbutton to Crop
H_crop = uicontrol(gcf,'style','pushbutton',...
   'units','normalized',...
   'position',[0.025 0.870 0.075 0.04],...
   'string','Crop',...
   'fontsize',14,...
   'tooltipstring','Crop Data to start of downcast / end of upcast',...
   'enable','off',...
   'callback',[...
        'global H;',...
        'global DATA;',...
        '[H,DATA]=p51_Crop(H,DATA);',...
        'p51_Reset(H,DATA);',...
        'p51_Plot_ROQ(H,DATA);']);   

% Pushbutton to SELECT/DELETE 
H_Delete = uicontrol(gcf,'style','pushbutton',...
   'units','normalized',...
   'position',[0.105 0.870 0.070 0.040],...
   'string','Select/Delete',...
   'fontsize',14,...
   'tooltipstring','Crop Data to start of downcast / end of upcast',...
   'enable','off',...
   'callback',[...
        'global H;',...
        'global DATA;',...
        '[H,DATA]=p51_Delete(H,DATA);',...
        'p51_Reset(H,DATA);',...
        'p51_Plot_ROQ(H,DATA);']);   
    
% Pushbutton to create Water Column Upcast/Downcast File
H_export_H2O = uicontrol(gcf,'style','pushbutton',...
   'units','normalized',...
   'position',[0.025 0.830 0.15 0.04],...
   'string','Create H2O Col File(s)',...
   'fontsize',14,...
   'enable','off',...
   'tooltipstring','Export water column data during down and/or up casts',...
   'callback',[...
        'global H;',...
        'global DATA;',...
        'p51_ExportH2O(H,DATA);',...
        'p51_PlotCasts(H);']);
   
% Pushbutton to create Penfile
H_export_penfile = uicontrol(gcf,'style','pushbutton',...
   'units','normalized',...
   'position',[0.025 0.790 0.15 0.04],...
   'string','Create Penfile',...
   'fontsize',14,...
   'enable','off',...
   'tooltipstring','Create a penfile after selecting W1, W2,P, H, and E (below)',...
   'callback',[...
       'p51_CreatePenfile_ROQ(H,DATA);',...
       ]);

% Pushbutton to create ASCII Text File of All Data
H_export_ascii = uicontrol(gcf,'style','pushbutton',...
   'units','normalized',...
   'position',[0.025 0.752 0.150 0.040],...
   'string','Create ASCII File',...
   'fontsize',14,...
   'enable','off',...
   'tooltipstring','Export ascii text file of entire deployment record',...
   'callback',[...
        'global H;',...
        'global DATA;',...
        'p51_ExportAscii_ROQ(H,DATA);']);

% % FILTER PARAMETERS

% Filter Window Static Text 
filterstr ={'Filter' 'Windows'};
 H_Static_Filter = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.105 0.916 0.040 0.040],...
   'string',filterstr,...
   'horizontalalignment','center',...
   'fontsize',12,...
   'tooltipstring','Running Median, Running Mean, and Decimate filter window lengths',...
   'backgroundcolor',[0.75 0.75 0.75]);   
    
% Filter Window Lengths
 H_Filter = uicontrol(gcf,'style','edit',...
   'units','normalized',...
   'position',[0.148 0.920 0.025 0.040],...
   'string','2 6 10',...
   'horizontalalignment','center',...
   'fontsize',12,...
   'tooltipstring','Running Median, Running Mean, and Decimate filter window lengths',...
   'backgroundcolor',[1 1 1]);
% --------------------------------------------
% Frame and display for Datafile info

% Frame for datafile info
H_frame_info = uicontrol(gcf,'style','frame',...
   'units','normalized',...
   'position',[0.015 0.495 0.170 0.250],...
   'backgroundcolor',[0.5 0.5 0.5]);

% Static text saying "Datafile Info"
H_static_info = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.025 0.700 0.150 0.040],...
   'string','Datafile Information',...
   'fontweight','b',...
   'fontsize',14,...
   'foregroundcolor','y',...
   'backgroundcolor',[0.5 0.5 0.5]);

% Filename ----->
% Static text that says "Filename:"
H_static_filename = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.025 0.685 0.050 0.025],...
   'string','Filename:',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Text that displays Filename
H_filename = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.080 0.685 0.100 0.025],...
   'string','default',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Static text that says "Start Date"
H_static_start_date = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.025 0.655 0.050 0.025],...
   'string','Start Date:',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Text that displays Starting date
H_start_date = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.080 0.655 0.100 0.025],...
   'string','default',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Static text that says "Start Time:"
H_static_start_time = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.025 0.625 0.05 0.025],...
   'string','Start Time:',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Text that displays Start Time
H_start_time = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.080 0.625 0.100 0.025],...
   'string','default',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Static text that says "End Time:"
H_static_end_time = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.025 0.595 0.05 0.025],...
   'string','End Time:',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Text that displays End Time
H_end_time = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.080 0.595 0.100 0.025],...
   'string','default',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Static text that says "Log Interval:"
H_static_logint = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.025 0.565 0.05 0.025],...
   'string','Log Int (s):',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Text that displays Log Interval
H_logint = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.080 0.565 0.100 0.025],...
   'string','default',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Static text that says "Decay (min)" [Frictional Decay]
H_static_decay = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.025 0.535 0.05 0.025],...
   'string','Decay (min):',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Text that displays Decay [Frictional Decay]
H_decay = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.080 0.535 0.100 0.025],...
   'string','default',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Static text that says "Pulse (sec)" [Heat Pulse]
H_static_pulse = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.025 0.505 0.05 0.025],...
   'string','Pulse (sec):',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Static text that displays Pulse [Heat Pulse]
H_pulse = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.080 0.505 0.100 0.025],...
   'string','default',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% --------------------------------------------
% Frame and display for Selection info

% Frame for Selection info
H_frame_selected = uicontrol(gcf,'style','frame',...
   'units','normalized',...
   'position',[0.015 0.170 0.170 0.320],...
   'backgroundcolor',[0.5 0.5 0.5]);

% Fame for Down/UpCast
H_frame_updown = uicontrol(gcf,'style','frame',...
    'units','normalized',...
    'position',[0.015 0.170 0.170 0.160],...
    'backgroundcolor',[0.5 0.5 0.5]);


% Popupmenu for "Selections"
H_Select = uicontrol(gcf,'style','popupmenu',...
   'units','normalized',...
   'position',[0.025 0.445 0.15 0.04],...
   'string','Selections | Clear | Start Downcast | End Downcast | Start Upcast | End Upcast | Start Eqm (W1)| End Eqm (W2) | Start Pen (P)| Start Heat (H)| End Pen (E)',...
   'fontweight','b',...
   'fontsize',14,...
   'foregroundcolor','k',...
   'horizontalalignment','center',...
   'backgroundcolor',[1 1 1],...
   'enable','off',...
   'tooltipstring','Click to graphically select data for creating penfiles and water column files',...
   'callback',[...
        'global H;',...
        'global DATA;',...
        'p51_Select_ROQ(H,DATA);']);
   
% Static text that says "Start Downcast"
H_static_StartDown = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.025 0.425 0.075 0.025],...
   'string','Start Downcast:',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Static text that displays Starting Downcast Record Number
H_StartDown = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.090 0.425 0.080 0.025],...
   'string','default',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Static text that says "End Downcast"
H_static_EndDown = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.025 0.395 0.075 0.025],...
   'string','End Downcast:',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Static text that displays Ending Downcast Record Number
H_EndDown = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.090 0.395 0.080 0.025],...
   'string','default',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Static text that says "Start Upcast"
H_static_StartUp = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.025 0.365 0.075 0.025],...
   'string','Start Upcast:',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Static text that displays Starting Upcast Record Number
H_StartUp = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.090 0.365 0.080 0.025],...
   'string','default',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Static text that says "End Upcast"
H_static_EndUp = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.025 0.335 0.075 0.025],...
   'string','End Upcast:',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Static text that displays Ending Upcast Record Number
H_EndUp = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.090 0.335 0.080 0.025],...
   'string','default',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% -------

% Static text that says "Start Eqm"
H_static_StartEqm = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.025 0.300 0.075 0.025],...
   'string','Start Eqm (W1):',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Static text that displays Starting Equilibrium Record Number
H_StartEqm = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.090 0.300 0.080 0.025],...
   'string','default',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Static text that says "End Eqm"
H_static_EndEqm = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.025 0.270 0.075 0.025],...
   'string','End Eqm (W2):',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Static text that displays Ending Equilibrium Record Number
H_EndEqm = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.090 0.270 0.080 0.025],...
   'string','default',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Static text that says "Start Pen"
H_static_Pen = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.025 0.240 0.075 0.025],...
   'string','Start Pen (P):',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Static text that displays Penetration Record Number
H_Pen = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.090 0.240 0.080 0.025],...
   'string','default',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Static text that says "Start Heat"
H_static_Heat = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.025 0.210 0.075 0.025],...
   'string','Start Heat (H):',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Static text that displays Heat Record Number
H_Heat = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.090 0.210 0.080 0.025],...
   'string','default',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Static text that says "End Pen"
H_static_End = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.025 0.180 0.075 0.025],...
   'string','End Pen (E):',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);

% Static text that displays Ending Pen Record Number
H_End = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.090 0.180 0.080 0.025],...
   'string','default',...
   'horizontalalignment','left',...
   'fontsize',12,...
   'backgroundcolor',[0.5 0.5 0.5]);



% ---------------------
% PLOT CONTROLS

% Frame for zoom and pan controls
H_frame_plotcontrols = uicontrol(gcf,'style','frame',...
   'units','normalized',...
   'position',[0.015 0.105 0.17 0.060],...
   'backgroundcolor',[0.5 0.5 0.5]);

% Static text saying "Plot Controls"
H_static_info = uicontrol(gcf,'style','text',...
   'units','normalized',...
   'position',[0.025 0.134 0.15 0.030],...
   'string','Plot Controls',...
   'fontweight','b',...
   'fontsize',14,...
   'foregroundcolor','y',...
   'backgroundcolor',[0.5 0.5 0.5]);

% DECIMATED Plot Select
H_decp = uicontrol(gcf,'Style','checkbox',...
   'units','normalized',...
   'Position',[0.018 0.112 0.030 0.025],...
   'String','Dec',...
   'horizontalalignment','left',...
   'fontsize',8,...
   'backgroundcolor',[1 1 1],...
   'value',1,...
   'enable','off',...
   'tooltipstring','Make Decimated Data Visible',...
   'Callback',[...
      'global H;',...
      'p51_PlotSelect(H);']);
  
% CLEAN Plot Select
H_clnp = uicontrol(gcf,'Style','checkbox',...
   'units','normalized',...
   'Position',[0.049 0.112 0.030 0.025],...
   'String','Cln',...
   'horizontalalignment','left',...
   'fontsize',8,...
   'backgroundcolor',[1 1 1],...
   'value',1,...
   'enable','off',...
   'tooltipstring','Make Clean (no negative numbers) Data Visible',...
   'Callback',[...
      'global H;',...
      'p51_PlotSelect(H);']);


% RAW Plot Select
H_rawp = uicontrol(gcf,'Style','checkbox',...
   'units','normalized',...
   'Position',[0.080 0.112 0.030 0.025],...
   'String','Raw',...
   'horizontalalignment','left',...
   'fontsize',8,...
   'backgroundcolor',[1 1 1],...
   'value',0,...
   'enable','off',...
   'tooltipstring','Make Raw Data Visible',...
   'Callback',[...
      'global H;',...
      'p51_PlotSelect(H);']);

% ZOOM
H_zoom = uicontrol(gcf,'Style','checkbox',...
   'units','normalized',...
   'Position',[0.119 0.112 0.030 0.025],...
   'String','Zoom',...
   'horizontalalignment','left',...
   'fontsize',8,...
   'backgroundcolor',[1 1 1],...
   'tooltipstring','Toggle Zoom on/off',...
   'Callback',[...
      'global H;',...
      'zoom off;',...
      'if H.Plot_Controls.Zoom.Value==1;',...
      '   zoom on;',...
      '   H.Plot_Controls.Pan.Value=0;',...
      '   pan off;',...
      'end']);

% PAN 
H_pan = uicontrol(gcf,'Style','checkbox',...
   'units','normalized',...
   'Position',[0.150 0.112 0.030 0.025],...
   'String','Pan',...
   'horizontalalignment','left',...
   'fontsize',8,...
   'backgroundcolor',[1 1 1],...
   'tooltipstring','Toggle Pan on/off',...
   'Callback',[...
      'global H;',...
      'pan off;',...
      'if H.Plot_Controls.Pan.Value==1;',...
      '   pan on;',...
      '   H.Plot_Controls.Zoom.Value=0;',...
      '   zoom off;',...
      'end']);

% --------------------------------------
% Screengrab & Quit
H_frame_quit = uicontrol(gcf,'style','frame',...
   'units','normalized',...
   'position',[0.015 0.027 0.17 0.055],...
   'backgroundcolor',[0.5 0.5 0.5]);

% Pushbutton to Quit
H_quit = uicontrol(gcf,'style','pushbutton',...
   'units','normalized',...
   'position',[0.020 0.036 0.080 0.04],...
   'string','Quit',...
   'fontsize',16,...
   'tooltipstring','Exit Pro51',...
   'callback',[...
       'global H_figure;',...
       'close(H_figure);',...
       'clear']);

% Pushbutton to Screengrab
H_screengrab = uicontrol(gcf,'style','pushbutton',...
   'units','normalized',...
   'position',[0.101 0.036 0.080 0.04],...
   'string','Screengrab',...
   'fontsize',16,...
   'tooltipstring','Create a screengrab of the current image',...
   'enable','off',...
   'callback','p51_ScreenGrab');

% % INITIALIZE

% Initialize Selection Vectors. Initially format for 22 thermistors
foo = zeros(1,22);
foo = foo/0;
h_selected_raw       = foo;   % handle for lines showing picks on raw axis
h_selected_depth     = foo;   % handle for lines showing picks on depth axis
h_selected_accel     = foo;   % handle for lines showing picks on acceleration axis
h_selected_tilt      = foo;   % handle for lines showing picks on tilt axis
h_selected_raw_txt   = foo;   % handle for text showing picks on raw axis
h_selected_depth_txt = foo;   % handle for text showing picks on depth axis
h_selected_accel_txt = foo;   % handle for text showing picks on acceleration axis
h_selected_tilt_txt  = foo;   % handle for text showing picks on tilt axis

% Data
Traw   = 0;
Tcln   = 0;
Pitch  = 0;
Roll   = 0;
G      = 0;
Tilt   = 0;
Time   = 0;
Params = {'default'};

% Errors
ErrorFlag = 0;

% Crop Applied
CropFlag = 0;

% % HIDDEN HANDLES FOR SELECTION VECTORS

H_Selected_raw = uicontrol(gcf,'style','edit',...
    'string','default',...
    'visible','off',...
    'value',h_selected_raw);

H_Selected_depth = uicontrol(gcf,'style','edit',...
    'string','default',...
    'visible','off',...
    'value',h_selected_depth);

H_Selected_accel = uicontrol(gcf,'style','edit',...
    'string','default',...
    'visible','off',...
    'value',h_selected_accel);

H_Selected_tilt = uicontrol(gcf,'style','edit',...
    'string','default',...
    'visible','off',...
    'value',h_selected_tilt);

H_Selected_raw_text = uicontrol(gcf,'style','edit',...
    'string','default',...
    'visible','off',...
    'value',h_selected_raw_txt);

H_Selected_depth_text = uicontrol(gcf,'style','edit',...
    'string','default',...
    'visible','off',...
    'value',h_selected_depth_txt);

H_Selected_accel_text = uicontrol(gcf,'style','edit',...
    'string','default',...
    'visible','off',...
    'value',h_selected_accel_txt);

H_Selected_tilt_text = uicontrol(gcf,'style','edit',...
    'string','default',...
    'visible','off',...
    'value',h_selected_tilt_txt);

H_LegendSelect = uicontrol(gcf,'style','edit',...
    'string','default',...
    'visible','off',...
    'value',[]); 

% % HIDDEN HANDLES FOR AXES LIMITS
H_AxLims_Raw = uicontrol(gcf,'style','edit',...
    'string','default',...
    'visible','off');

H_AxLims_Tilt = uicontrol(gcf,'style','edit',...
    'string','default',...
    'visible','off');

H_AxLims_Depth = uicontrol(gcf,'style','edit',...
    'string','default',...
    'visible','off');

H_AxLims_Acc = uicontrol(gcf,'style','edit',...
    'string','default',...
    'visible','off');

S_AxLims = struct('AxLims_Raw',H_AxLims_Raw,...
    'AxLims_Depth',H_AxLims_Depth,...
    'AxLims_Tilt',H_AxLims_Tilt,'AxLims_Acc',H_AxLims_Acc);

% % OTHER HIDDEN HANDLES
H_NoThermistors = uicontrol(gcf,'style','edit',...
    'string','default',...
    'visible','off');

% % STRUCTURES

% Structure Containing Axes Handles
S_Axes = struct('Raw',H_axis_raw,'Depth',H_axis_depth,...
    'Tilt',H_axis_tilt,'Accel',H_axis_accel);

% Structure Containing Axes Limits
S_AxLims = struct('AxLims_Raw',H_AxLims_Raw,...
    'AxLims_Depth',H_AxLims_Depth,...
    'AxLims_Tilt',H_AxLims_Tilt,'AxLims_Acc',H_AxLims_Acc);

% Structure Containing Executable Control Handles and Filter Window Lengths
S_Exe_Controls = struct('Load',H_load,'Crop',H_crop,...
    'Export_H2O',H_export_H2O,...
    'Export_Penfile',H_export_penfile,'Export_Ascii',H_export_ascii,...
    'Selection',H_Select,'Delete',H_Delete,'Filter_WL',H_Filter);

% Structure Containing Handles for Selection Record Numbers
S_Selections = struct('Select',H_Select,...
    'Start_Downcast',H_StartDown,...
    'End_Downcast',H_EndDown,'Start_Upcast',H_StartUp,...
    'End_Upcast',H_EndUp,'Start_Eqm',H_StartEqm,...
    'End_Eqm',H_EndEqm,'Start_Pen',H_Pen,'Start_Heat',H_Heat,...
    'End_Pen',H_End);

% Structure Containing Plot Control Handles and Quit/Screengrab
S_Plot_Controls = struct('Zoom',H_zoom,'Pan',H_pan,...
    'RawPlot',H_rawp,'CleanPlot',H_clnp','DecimatedPlot',H_decp,...
    'Screengrab',H_screengrab,'Quit',H_quit,'Legend',H_LegendSelect);

%Structure Containing Handles for Selection Vertical Line Plotting
S_Selections_Lines = struct('Raw',H_Selected_raw,'Depth',H_Selected_depth',...
    'Tilt',H_Selected_tilt,'Accel',H_Selected_accel,...
    'Raw_Text',H_Selected_raw_text,...
    'Depth_Text',H_Selected_depth_text,'Tilt_Text',H_Selected_tilt_text,...
    'Accel_Text',H_Selected_accel_text);

% Structure Containing Datafile information
S_FileInfo = struct('Filename',H_filename,'Start_Date',H_start_date,...
    'Start_Time',H_start_time,'End_Time',H_end_time,...
    'Log_Interval',H_logint,'Decay_Time',H_decay,'Pulse_Length',H_pulse,...
    'No_Thermistors',H_NoThermistors);

% ----- Structure Containing All Previous Structures ----- %
H = struct('Fileinfo',S_FileInfo,'Axes',S_Axes,...
    'Exe_Controls',S_Exe_Controls,...
    'Selections',S_Selections,'Selections_Lines',S_Selections_Lines,...
    'Plot_Controls',S_Plot_Controls,'Axis_Limits',S_AxLims,...
    'Error',ErrorFlag,'Crop',CropFlag);

